services:
  samba:
    image: dockurr/samba:latest
    hostname: samba
    environment:
      GID: ${UPGID}
      UID: ${UPUID}
      NAME: "Home"
      USER: ${SAMBA_USER}
      PASS: ${PASSWORD}
    volumes:
      - ${HOME_DIR}:/storage
    networks:
      cloudflared:
        ipv4_address: 10.7.0.100
    restart: on-failure

networks:
  cloudflared:
    external: true
