services:
  samba:
    hostname: samba
    image: dockurr/samba:latest
    user: "${PUID}:${PGID}"
    environment:
      - GID=${UPGID}
      - NAME=${SAMBA_NAME}
      - USER=${SAMBA_USER}
      - PASS=${SAMBA_PASS}  # Ensure the password is secure
    volumes:
      - ${HOME_DIR}:/storage
    networks:
      cloudflared:
        ipv4_address: 10.7.0.100  # Assigning a static IP from the cloudflared network
    restart: on-failure

networks:
  cloudflared:
    external: true
