services:
  filebrowser:
    hostname: filebrowser
    image: filebrowser/filebrowser:s6
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /home/ubuntu/:/srv
      - /home/ubuntu/portainer/filebrowser/config:/config
    networks:
      cloudflared:
        aliases:
          - filebrowser
    restart: always
    # ports:
    #   - "8080:80"

networks:
  cloudflared:
    external: true
