version: "3.8"

services:
  firefox:
    hostname: firefox
    image: jlesage/firefox:latest
    volumes:
      - firefox_data:/config:rw
    environment:
      - VNC_LISTENING_PORT=5900
      - VNC_PASSWORD=shit####  # Ensure to change the password to something more secure
      - TZ=Asia/Dhaka
    networks:
      - cloudflared
    restart: on-failure

volumes:
  firefox_data:

networks:
  cloudflared:
    external: true
