services:
  portainer:
    hostname: portainer
    image: portainer/portainer-ce:lts
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data
    networks:
      cloudflared:
        aliases:
          - portainer
    restart: always
    # ports:
    #   - "8000:8000"
    #   - "9443:9443"

  cloudflared:
    hostname: cloudflared
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token <cloudflaretokenhere>
    networks:
      cloudflared:
        aliases:
          - cloudflared
    restart: always

networks:
  cloudflared:
    external: true
