version: '3.8'

services:
  portainer:
    image: portainer/portainer-ce:lts
    container_name: portainer
    restart: always
    # ports:
    #   - "8000:8000"
    #   - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data
    networks:
      cloudflared:
        aliases:
          - portainer
    hostname: portainer

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel --no-autoupdate run --token <cloudflaretokenhere>
    restart: always
    networks:
      cloudflared:
        aliases:
          - cloudflared
    hostname: cloudflared

networks:
  cloudflared:
    external:
      name: cloudflared
