version: "3.8"

services:
  samba:
    image: dockurr/samba:latest
    hostname: samba 
    user: "0:0"
    environment:
      NAME: "Home"  
      USER: "whatisthis"  
      PASS: "whatsoever##"  
    # ports:
    #   - "445:445"  
    volumes:
      - /home/ubuntu:/storage 
    networks:
      cloudflared:
        aliases:
          - samba  
    restart: on-failure  

networks:
  cloudflared:
    external: true  
