services:
  samba:
    image: dockurr/samba:latest
    hostname: samba
    user: "0:0"
    environment:
      GID: "1001" # User specific
      NAME: "Home"
      USER: "whatisthis"
      PASS: "whatsoever##"  # Ensure the password is secure
    # ports:
    #   - "445:445"
    volumes:
      - /home/ubuntu:/storage
    networks:
      cloudflared:
        aliases:
          - samba
    restart: on-failure

networks:
  cloudflared:
    external: true
