version: '3.8'

services:
  wg-easy:
    hostname: wgeasy
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    environment:
      - LANG=en  
      - WG_HOST=***********  # Replace with your actual host URL or IP
      - PASSWORD_HASH=$$2y$$10$$*********************  # Use double $$ for the password hash
      - PORT=51821  
      - WG_PORT=51820  
    volumes:
      - ~/.wg-easy:/etc/wireguard  # Ensure the path is correct for your setup
      # - /lib/modules:/lib/modules  # Uncomment if running on Alpine
    ports:
      - "51820:51820/udp"  # WireGuard UDP port
      # - "51821:51821/tcp"  # Uncomment if you need this port exposed
    cap_add:
      - NET_ADMIN  
      - SYS_MODULE
    sysctls:
      - 'net.ipv4.conf.all.src_valid_mark=1'
      - 'net.ipv4.ip_forward=1'
    restart: unless-stopped
    networks:
      cloudflared:
        aliases:
          - wg-easy
    privileged: true  # Required for some network operations in WireGuard

networks:
  cloudflared:
    external: true

volumes:
  wg-easy-config:
    driver: local
