services:
  filebrowser:
    hostname: filebrowser
    image: filebrowser/filebrowser:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${HOME_DIR}:/srv
      - ${HOME_DIR}/docker/filebrowser/database.db:/database.db
    networks:
      cloudflared:
        aliases:
          - filebrowser
    restart: always
    # ports:
    #   - "8080:80"

networks:
  cloudflared:
    external: true
