services:
  filebrowser:
    hostname: filebrowser
    image: filebrowser/filebrowser:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${HOME_DIR}:/srv
      - ${HOME_DIR}/docker/filebrowser/database.db:/database.db
      - ${HOME_DIR}/docker/filebrowser/.filebrowser.json:/.filebrowser.json
    networks:
      cloudflared:
        aliases:
          - filebrowser
    restart: always
    # ports:
    #   - "8080:80"
    env_file:
      - /home/ubuntu/docker/portainer/.env  # Pointing to your .env file

networks:
  cloudflared:
    external: true
