services:
  transfer:
    image: dutchcoders/transfer.sh:latest
    hostname: transfersh
    restart: on-failure
    command: --provider local --basedir /tmp/
    environment:
      TZ: ${TZ}
    volumes:
      - transfer_data:/tmp/
    networks:
      cloudflared:
        aliases:
          - transfersh

volumes:
  transfer_data:

networks:
  cloudflared:
    external: true
