services:
  uptimekuma:
    image: louislam/uptime-kuma:latest
    hostname: uptimekuma
    restart: unless-stopped
    environment:
      TZ: ${TZ}
    volumes:
      - ${HOME_DIR}/docker/uptimekuma:/app/data
    networks:
      cloudflared:
        aliases:
          - uptimekuma
    # ports:
    #   - "3001:3001"  # Web UI

networks:
  cloudflared:
    external: true
