services:
  firefox:
    image: jlesage/firefox:latest
    hostname: firefox
    container_name: FireFox
    environment:
      VNC_LISTENING_PORT: "5900"
      VNC_PASSWORD: ${PASSWORD}
      TZ: ${TZ}
      DARK_MODE: "1"
      WEB_AUDIO: "1"
      LANG: "en_US.UTF-8"
    volumes:
      - firefox_data:/config:rw
    networks:
      cloudflared:
        aliases:
          - firefox
    restart: on-failure
    # ports:
    #   - "5900:5900"

volumes:
  firefox_data:

networks:
  cloudflared:
    external: true
