services:
  db:
    image: mysql:8.0
    hostname: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ${HOME_DIR}/docker/wordpress/db:/var/lib/mysql
    networks:
      cloudflared:
        aliases:
          - db
    # ports:
    #   - "3306:3306"

  wordpress:
    image: wordpress:latest
    hostname: wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    volumes:
      - ${HOME_DIR}/docker/wordpress/wordpress:/var/www/html
      - ${HOME_DIR}/docker/wordpress/php.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      cloudflared:
        aliases:
          - wordpress
    # ports:
    #   - "8080:80"

networks:
  cloudflared:
    external: true
