services:
  db:
    hostname: db
    image: mysql:8.0
    volumes:
      - ${HOME_DIR}/docker/wordpress/db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      cloudflared:
        aliases:
          - db

  wordpress:
    hostname: wordpress
    image: wordpress:latest
    restart: always
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    volumes:
      - ${HOME_DIR}/docker/wordpress/wordpress:/var/www/html
    networks:
      cloudflared:
        aliases:
          - wordpress

networks:
  cloudflared:
    external: true
