services:
  firefox:
    hostname: firefox
    image: jlesage/firefox:latest
    environment:
      - VNC_LISTENING_PORT=5900
      - VNC_PASSWORD=${PASSWORD}
      - TZ=${TZ}
    volumes:
      - firefox_data:/config:rw
    networks:
      cloudflared:
        aliases:
          - firefox
    restart: on-failure
    # ports:
    #   - "5900:5900"

volumes:
  firefox_data:

networks:
  cloudflared:
    external: true
