theme:
  background-color: 240 13 14
  primary-color: 51 33 68
  negative-color: 358 100 68
  contrast-multiplier: 1.2
pages:
  - name: SAPPHIRE
    # Optionally, if you only have a single page you can hide the desktop navigation for a cleaner look
    hide-desktop-navigation: true
    columns:
      - size: small
        widgets:
          - type: weather
            location: Dhaka, Bangladesh
            units: metric # alternatively "imperial"
            hour-format: 12h # alternatively "24h"
            # Optionally hide the location from being displayed in the widget
            # hide-location: true
          - type: calendar
            first-day-of-week: friday
          - type: markets
            markets:
              - symbol: GC=F
                name: Gold Future
                chart-link: https://www.tradingview.com/chart/?symbol=OANDA:XAUUSD
              - symbol: GBPJPY=X
                name: British Pound / Japanese Yen
                chart-link: https://www.tradingview.com/chart/?symbol=OANDA:GBPJPY
              - symbol: EURJPY=X
                name: Euro / Japanese Yen
                chart-link: https://www.tradingview.com/chart/?symbol=OANDA:EURJPY

      - size: full
        widgets:
          - type: clock
            hour-format: 12h
            timezones:
              - timezone: Asia/Dhaka
                label: Dhaka
          - type: search
            search-engine: google
          - type: server-stats
            servers:
              - type: local
                name: sapphire

      - size: small
        widgets:
          - type: monitor
            cache: 1m
            title: uptime
            sites:
              - title: Portainer
                url: https://portainer.rogx.cc
                # icon: /assets/jellyfin-logo.png
              - title: WebTop
                url: https://webtop.rogx.cc
                # icon: /assets/jellyfin-logo.png
                alt-status-codes:
                  - 401
              - title: RAFSuNX
                url: https://rafsunx.com
                # icon: /assets/jellyfin-logo.png
              - title: ROGx
                url: https://rogx.cc
                # icon: /assets/gitea-logo.png
              - title: INFOiyo
                url: https://infoiyo.cc
                # icon: /assets/immich-logo.png
              - title: SearXNG
                url: https://searxng.rogx.cc
                # icon: /assets/adguard-logo.png
          - type: docker-containers
            hide-by-default: false

branding:
  custom-footer: |
    <p>Powered by <a href="https://github.com/rafsunx/">RAFSuNX</a></p>
  # logo-url: /assets/logo.png
  # favicon-url: /assets/logo.png
