pages:
  - name: RAFSuNX
    # Optionally, if you only have a single page you can hide the desktop navigation for a cleaner look
    hide-desktop-navigation: true
    columns:
      - size: small
        widgets:
          - type: calendar
            first-day-of-week: friday
          - type: markets
            markets:
              - symbol: XAUUSD
                name: Gold
              - symbol: GBPJPY
                name: British Pound / Japanese Yen
              - symbol: EURJPY
                name: Euro / Japanese Yen

      - size: full
        widgets:
          - type: clock
            hour-format: 12h
            timezones:
              - timezone: Asia/Dhaka
                label: Dhaka
          - type: search
            search-engine: google


      - size: small
        widgets:
          - type: weather
            location: Dhaka, Bangladesh
            units: metric # alternatively "imperial"
            hour-format: 12h # alternatively "24h"
            # Optionally hide the location from being displayed in the widget
            # hide-location: true



          - type: releases
            cache: 1d
            # Without authentication the Github API allows for up to 60 requests per hour. You can create a
            # read-only token from your Github account settings and use it here to increase the limit.
            # token: ...
            repositories:
              - glanceapp/glance
              - go-gitea/gitea
              - immich-app/immich
              - syncthing/syncthing

  # Add more pages here:
  # - name: Your page name
  #   columns:
  #     - size: small
  #       widgets:
  #         # Add widgets here

  #     - size: full
  #       widgets:
  #         # Add widgets here

  #     - size: small
  #       widgets:
  #         # Add widgets here
