services:
  glance:
    image: glanceapp/glance:latest
    hostname: glance
    restart: unless-stopped
    volumes:
      - ${HOME_DIR}/docker/portainer/config/compose/13/glance/config:/app/config
    networks:
      cloudflared:
        aliases:
          - glance
    # ports:
    #   - "8080:8080"

networks:
  cloudflared:
    external: true
