services:
  searxng:
    image: docker.io/searxng/searxng:2025.5.18-5dff826
    hostname: searxng
    container_name: SearXNG
    environment:
      SEARXNG_BASE_URL: ${SEARXNG_BASE_URL}
    volumes:
      - searxng_data:/etc/searxng
    networks:
      cloudflared:
        aliases:
          - searxng
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "5"
    restart: on-failure

volumes:
  searxng_data:

networks:
  cloudflared:
    external: true
