services:
  searxng:
    image: docker.io/searxng/searxng:latest
    hostname: searxng
    container_name: SearXNG
    environment:
      SEARXNG_BASE_URL: ${SEARXNG_BASE_URL}
      SEARXNG_REDIS_URL: redis://redis:6379/0
      PUID: ${UPUID}
      PGID: ${UPGID}
    volumes:
      - ${HOME_DIR}/docker/searxng:/etc/searxng
      - type: tmpfs
        target: /tmp
    networks:
      cloudflared:
        aliases:
          - searxng
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "5"
    restart: on-failure
    # ports:
    #   - "8080:8080"

  redis:
    image: redis:alpine
    hostname: redis
    container_name: Redis
    restart: always
    networks:
      cloudflared:
        aliases:
          - redis
    # ports:
    #   - "6379:6379"

networks:
  cloudflared:
    external: true
