services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:latest
    hostname: wireguard
    restart: unless-stopped
    privileged: true
    environment:
      LANG: "en"
      WG_HOST: ${WG_HOST}
      PASSWORD_HASH: ${WG_PASSWORD_HASH}
      PORT: "51821"
      WG_PORT: "51820"
    volumes:
      - ~/.wg-easy:/etc/wireguard
      - /lib/modules:/lib/modules  # Kernel module mount (uncomment if needed)
    ports:
      - "51820:51820/udp"
      # - "51821:51821/tcp"  # Web UI port (uncomment if needed)
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    networks:
      cloudflared:
        aliases:
          - wg-easy

volumes:
  wg-easy-config:
    driver: local

networks:
  cloudflared:
    external: true
